export const DEMO_FALLBACK_PHONE_NUMBER = "2298293537";

export const INSURANCE_ADAPTER_ENV_KEY = "INS_NAV_INSURANCE_ADAPTER";
export const DEFAULT_INSURANCE_ADAPTER = "mock";

export const INSURER_LOOKUP: Record<string, string> = {
  "blue cross": DEMO_FALLBACK_PHONE_NUMBER,
  "blue shield": DEMO_FALLBACK_PHONE_NUMBER,
  bcbs: DEMO_FALLBACK_PHONE_NUMBER,
  anthem: DEMO_FALLBACK_PHONE_NUMBER,
  united: DEMO_FALLBACK_PHONE_NUMBER,
  unitedhealthcare: DEMO_FALLBACK_PHONE_NUMBER,
  uhc: DEMO_FALLBACK_PHONE_NUMBER,
  optum: DEMO_FALLBACK_PHONE_NUMBER,
  aetna: DEMO_FALLBACK_PHONE_NUMBER,
  "cvs health": DEMO_FALLBACK_PHONE_NUMBER,
  cigna: DEMO_FALLBACK_PHONE_NUMBER,
  evernorth: DEMO_FALLBACK_PHONE_NUMBER,
  humana: DEMO_FALLBACK_PHONE_NUMBER,
  kaiser: DEMO_FALLBACK_PHONE_NUMBER,
  "kaiser permanente": DEMO_FALLBACK_PHONE_NUMBER,
  centene: DEMO_FALLBACK_PHONE_NUMBER,
  wellcare: DEMO_FALLBACK_PHONE_NUMBER,
  ambetter: DEMO_FALLBACK_PHONE_NUMBER,
  molina: DEMO_FALLBACK_PHONE_NUMBER,
  oscar: DEMO_FALLBACK_PHONE_NUMBER,
  elevance: DEMO_FALLBACK_PHONE_NUMBER,
  magellan: DEMO_FALLBACK_PHONE_NUMBER,
};
