export const DEMO_FALLBACK_PHONE_NUMBER = "2298293537";

export const INSURANCE_ADAPTER_ENV_KEY = "INS_NAV_INSURANCE_ADAPTER";
export const DEFAULT_INSURANCE_ADAPTER = "mock";
export const PROVIDER_SEARCH_ADAPTER_ENV_KEY = "INS_NAV_PROVIDER_SEARCH_ADAPTER";
export const DEFAULT_PROVIDER_SEARCH_ADAPTER = "mock";
export const PROVIDER_QUOTE_ADAPTER_ENV_KEY = "INS_NAV_PROVIDER_QUOTE_ADAPTER";
export const DEFAULT_PROVIDER_QUOTE_ADAPTER = "mock";
export const BOOKING_ADAPTER_ENV_KEY = "INS_NAV_BOOKING_ADAPTER";
export const DEFAULT_BOOKING_ADAPTER = "mock";
export const INS_NAV_AGENT_LOOP_ENV_KEY = "INS_NAV_AGENT_LOOP";
export const INS_NAV_AGENT_LOOP_DEFAULT = "pipeline";
export const INS_NAV_PROVIDER_CALL_LIMIT = 2;
export const INS_NAV_GROK_VOICE_MODEL_ENV_KEY = "INS_NAV_GROK_VOICE_MODEL";
export const INS_NAV_GROK_VOICE_MODEL_DEFAULT = "grok-voice-think-fast-1.1";
export const INS_NAV_GROK_VOICE_NAME_ENV_KEY = "INS_NAV_GROK_VOICE_NAME";
export const INS_NAV_GROK_VOICE_NAME_DEFAULT = "sal";
export const INS_NAV_PROVIDER_PRICING_CALL_TO_ENV_KEY = "INS_NAV_PROVIDER_PRICING_CALL_TO";
export const INS_NAV_PROVIDER_PRICING_CALL_TO_DEFAULT = "+17043885498";
export const TELEPHONY_BRIDGE_INTERNAL_URL_ENV_KEY = "TELEPHONY_BRIDGE_INTERNAL_URL";
export const TELEPHONY_BRIDGE_INTERNAL_URL_DEFAULT = "http://localhost:8788";

export const INSURER_LOOKUP: Record<string, string> = {
  "blue cross": DEMO_FALLBACK_PHONE_NUMBER,
  "blue shield": DEMO_FALLBACK_PHONE_NUMBER,
  bcbs: DEMO_FALLBACK_PHONE_NUMBER,
  anthem: DEMO_FALLBACK_PHONE_NUMBER,
  united: DEMO_FALLBACK_PHONE_NUMBER,
  unitedhealthcare: DEMO_FALLBACK_PHONE_NUMBER,
  uhc: DEMO_FALLBACK_PHONE_NUMBER,
  optum: DEMO_FALLBACK_PHONE_NUMBER,
  aetna: DEMO_FALLBACK_PHONE_NUMBER,
  "cvs health": DEMO_FALLBACK_PHONE_NUMBER,
  cigna: DEMO_FALLBACK_PHONE_NUMBER,
  evernorth: DEMO_FALLBACK_PHONE_NUMBER,
  humana: DEMO_FALLBACK_PHONE_NUMBER,
  kaiser: DEMO_FALLBACK_PHONE_NUMBER,
  "kaiser permanente": DEMO_FALLBACK_PHONE_NUMBER,
  centene: DEMO_FALLBACK_PHONE_NUMBER,
  wellcare: DEMO_FALLBACK_PHONE_NUMBER,
  ambetter: DEMO_FALLBACK_PHONE_NUMBER,
  molina: DEMO_FALLBACK_PHONE_NUMBER,
  oscar: DEMO_FALLBACK_PHONE_NUMBER,
  elevance: DEMO_FALLBACK_PHONE_NUMBER,
  magellan: DEMO_FALLBACK_PHONE_NUMBER,
};
